config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # A rota é feita de:
  # 1) Verbo HTTP (GET / POST / PATCH / PUT / DELETE)
  # 2) Caminho Relativo da Url (/, ou /adilson, ou /bands)
  # 3) Qual controller responde à essa requisição
  # 4) Qual ação desse controller vai ser executada

  # verbo 'caminho', to: 'controller#ação', as: 'prefix_name'
  get '/home', to: 'pages#home', as: 'home'
  get '/about', to: 'pages#about_us', as: 'about'

  # É para mudar a página sem path (tudo dpos da /) da aplicação
  root to: 'pages#home'

  get '/mastodon', to: 'bands#best'

end

# 1a coisa a fazer: pensar na rota!!!!
# 2a coisa a fazer: ir no controller e codar o que precisa
# 3a coisa a fazer: implementar a view!

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def best
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # O quê é uma ação (action)??
  # Um método definido dentro de um Controller

  # Variável de instância
  # Permite compartilhar uma variável em uma ação do controller
  # com a view de mesmo nome!
  def home
    @bands = ["Mastodon", "Arcadea", "Black Sabbath", "Pink Floyd"]

    if params[:band_name]
      @bands = @bands.select { |band| band == params[:band_name] }
    end
  end

  # IMPORTANTE!!
  # A variável de instância definida dentro de uma ação
  # NÃO É COMPARTILHADA com as outras ações
  def about_us
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bands/best.html.erb
<h1>HA, MELHOR BANDA??</h1>
<h2>Mastodon!</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BestBandsRailsIntro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li>
        <%= link_to "Homepage", home_path %>
      </li>
      <li>
        <%= link_to "About us", about_path %>
      </li>
    </ul>
    <%= yield %>
    <h1>O footer...</h1>
  </body>
</html>

app/views/pages/about_us.html.erb
<h2>Here's some information about the partners:</h2>

<p>Matheus has been developing software since...</p>

app/views/pages/home.html.erb
<h2>Welcome to the Best Bands Awards</h2>


<ul>
  <% @bands.each do |band| %>
    <li><%= band %></li>
  <% end %>
</ul>

<!-- nome dos parâmetros que chegam no controller
     vem do nome dos inputs de um formulário -->
<!-- o formulário pode fazer a requisição para outra rota
     pois vai funcionar da mesma maneira :ok -->
<form action="/about" method='GET'>
  <input type="text" name="band_name" value="<%= params[:band_name] %>" placeholder="Escreva o nome da banda...">
  <input type="text" name="football_team">
  <input type="submit" value="Pesquise!">
</form>